<script setup>
import { computed, ref } from "vue";
import SymbolBadge from "./SymbolBadge.vue";
import StatusControl from "./StatusControl.vue";
import DisclosureChevron from "./DisclosureChevron.vue";
import { STATUS_LABELS, entryRecordOf, statusOf, updateEntry } from "../composables/useProgress.js";
import { useListView } from "../composables/useListView.js";

const props = defineProps({ entry: { type: Object, required: true } });

const { expandedIds, statusOpenIds, toggleExpanded, toggleStatusOpen } = useListView();

const status = computed(() => statusOf(props.entry.id));
const record = computed(() => entryRecordOf(props.entry.id));
const isExpanded = computed(() => expandedIds.value.has(props.entry.id));
const isStatusOpen = computed(() => statusOpenIds.value.has(props.entry.id));

const bodyId = computed(() => `body-${props.entry.id}`);
const statusPanelId = computed(() => `status-${props.entry.id}`);
const notesId = computed(() => `notes-${props.entry.id}`);

const notesVisible = ref(Boolean(record.value?.notes));

const statusChangedLabel = computed(() => {
	const changedAt = record.value?.statusChangedAt;
	if (!changedAt || status.value === "open") return "";
	const date = new Date(changedAt).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
	return `${STATUS_LABELS[status.value]} ${date}`;
});

// Some sites use one URL for both search and opt-out; show a single link then.
const links = computed(() => {
	const { searchUrl, optOutUrl } = props.entry;
	if (searchUrl && searchUrl === optOutUrl) return [{ url: searchUrl, label: "Search & opt-out page" }];
	const list = [];
	if (searchUrl) list.push({ url: searchUrl, label: "Search page" });
	if (optOutUrl) list.push({ url: optOutUrl, label: "Opt-out page" });
	return list;
});

function setStatus(newStatus) {
	updateEntry(props.entry.id, { status: newStatus });
}

function setNotes(event) {
	updateEntry(props.entry.id, { notes: event.target.value });
}
</script>

<template>
	<article class="entry" :data-status="status" :class="{ expanded: isExpanded }">
		<div class="entry-head">
			<button
				type="button"
				class="disclosure"
				:aria-expanded="isExpanded"
				:aria-controls="bodyId"
				@click="toggleExpanded(entry.id)"
			>
				<DisclosureChevron />
				<span class="entry-name">{{ entry.name }}</span>
				<SymbolBadge v-for="symbol in entry.symbols" :key="symbol" :symbol="symbol" />
			</button>

			<button
				type="button"
				class="status-badge"
				:data-status="status"
				:aria-expanded="isStatusOpen"
				:aria-controls="statusPanelId"
				:title="`Change status for ${entry.name}`"
				@click="toggleStatusOpen(entry.id)"
			>
				{{ STATUS_LABELS[status] }}
			</button>
		</div>

		<div v-if="isStatusOpen" :id="statusPanelId" class="status-panel">
			<StatusControl
				:model-value="status"
				:entry-id="entry.id"
				:entry-name="entry.name"
				@update:model-value="setStatus"
			/>
			<p v-if="statusChangedLabel" class="status-note">{{ statusChangedLabel }}</p>
		</div>

		<div v-if="isExpanded" :id="bodyId" class="entry-body">
			<p v-if="links.length" class="links">
				<template v-for="(link, index) in links" :key="link.url">
					<span v-if="index > 0"> · </span>
					<a :href="link.url" target="_blank" rel="noopener noreferrer">{{ link.label }}</a>
				</template>
			</p>

			<details class="instructions">
				<summary>
					<DisclosureChevron />
					<span>Instructions</span>
				</summary>
				<!-- Generated by scripts/extract.py: text is escaped, only <p> and <a> are emitted -->
				<div v-html="entry.instructionsHtml"></div>
			</details>

			<button v-if="!notesVisible" type="button" class="add-note" @click="notesVisible = true">+ Add note</button>
			<p v-else class="notes-wrapper">
				<label :for="notesId">Notes</label>
				<textarea
					:id="notesId"
					class="notes"
					rows="2"
					:value="record?.notes ?? ''"
					@input="setNotes"
				></textarea>
			</p>
		</div>
	</article>
</template>

<style scoped>
.entry {
	border-bottom: 1px solid #1c1c1c;
}

.entry-head {
	display: flex;
	align-items: center;
	gap: 0.5em;
	min-height: 44px;
}

.disclosure {
	display: flex;
	align-items: center;
	gap: 0.4em;
	flex: 1 1 auto;
	min-width: 0;
	min-height: 44px;
	padding: 0.2em 0;
	font: inherit;
	font-size: 1em;
	color: inherit;
	text-align: left;
	background: none;
	border: 0;
	cursor: pointer;
}

.disclosure:hover .entry-name {
	color: #fff;
}

.disclosure .chevron {
	color: #666;
}

.entry.expanded .disclosure .chevron {
	transform: rotate(90deg);
}

.entry-name {
	overflow: hidden;
	text-overflow: ellipsis;
	white-space: nowrap;
	color: #ddd;
}

.entry[data-status="removed"] .entry-name {
	text-decoration: line-through;
	color: #7a7a7a;
}

.entry[data-status="not-present"] .entry-name {
	font-style: italic;
	color: #7a7a7a;
}

.status-badge {
	flex: none;
	min-height: 32px;
	padding: 0.15em 0.7em;
	font: inherit;
	font-size: 0.75em;
	border: 1px solid;
	border-radius: 999px;
	background: none;
	cursor: pointer;
	white-space: nowrap;
}

.status-badge[data-status="open"] { color: #999; border-color: #3a3a3a; }
.status-badge[data-status="requested"] { color: var(--status-requested); border-color: var(--status-requested); }
.status-badge[data-status="removed"] { color: var(--status-removed); border-color: var(--status-removed); }
.status-badge[data-status="not-present"] { color: var(--status-not-present); border-color: var(--status-not-present); }

.status-panel {
	padding: 0 0 0.75em 1.4em;
}

.status-note {
	margin: 0.4em 0 0;
	font-size: 0.75em;
	color: #777;
}

.entry-body {
	padding: 0 0 1em 1.4em;
}

.links {
	margin: 0 0 0.5em;
	font-size: 0.9em;
}

.instructions summary {
	cursor: pointer;
	font-size: 0.9em;
	color: #999;
	min-height: 32px;
	display: flex;
	align-items: center;
	gap: 0.4em;
	/* display:flex already drops the native marker; these keep it gone across
	   engines now that we draw our own chevron. */
	list-style: none;
}

.instructions summary::-webkit-details-marker {
	display: none;
}

.instructions summary:hover {
	color: #ddd;
}

.instructions[open] .chevron {
	transform: rotate(90deg);
}

.instructions :deep(p) {
	margin: 0.5em 0;
	font-size: 0.9em;
}

.add-note {
	margin-top: 0.6em;
	padding: 0.3em 0;
	font: inherit;
	font-size: 0.8em;
	color: #f9ba52;
	background: none;
	border: 0;
	cursor: pointer;
}

.notes-wrapper {
	margin: 0.6em 0 0;
}

.notes-wrapper label {
	display: block;
	font-size: 0.8em;
	color: #999;
}

.notes {
	width: 100%;
	box-sizing: border-box;
	font: inherit;
	font-size: 0.9em;
	color: inherit;
	background: #0d0d0d;
	border: 1px solid #333;
	border-radius: 4px;
	padding: 0.4em;
	resize: vertical;
}
</style>
