import listData from "./entries.json";

const STATUSES = ["open", "requested", "removed", "not-present"];
const STATUS_LABELS = { open: "Open", requested: "Requested", removed: "Removed", "not-present": "Not Present" };
// Finished entries collapse to their header and count toward progress
const DONE_STATUSES = new Set(["removed", "not-present"]);

const entryListElement = document.getElementById("entry-list");
const summaryElement = document.getElementById("summary");
const progressBarElement = document.getElementById("progress-bar");
const legendElement = document.getElementById("legend");
const filtersElement = document.getElementById("filters");
const saveStatusElement = document.getElementById("save-status");

// { [entryId]: { status, updatedAt } }
let progress = {};

function statusOf(entryId) {
	return progress[entryId]?.status ?? "open";
}

function createElement(tagName, attributes = {}, children = []) {
	const element = document.createElement(tagName);
	for (const [attributeName, attributeValue] of Object.entries(attributes)) {
		if (attributeName === "text") element.textContent = attributeValue;
		else element.setAttribute(attributeName, attributeValue);
	}
	element.append(...children);
	return element;
}

function createSymbol(symbol) {
	const meaning = listData.symbolMeanings[symbol];
	return createElement("span", { class: "symbol", title: meaning, "aria-label": meaning, role: "img", text: symbol });
}

function createExternalLink(url, label) {
	return createElement("a", { href: url, target: "_blank", rel: "noopener noreferrer", text: label });
}

function formatDate(isoTimestamp) {
	return new Date(isoTimestamp).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

function renderLegend() {
	legendElement.replaceChildren("Key: ");
	for (const [symbol, meaning] of Object.entries(listData.symbolMeanings)) {
		legendElement.append(createSymbol(symbol), ` ${meaning}. `);
	}
}

function renderEntry(entry) {
	const status = statusOf(entry.id);
	const article = createElement("article", { class: DONE_STATUSES.has(status) ? "entry done" : "entry", id: entry.id, "data-status": status });

	const heading = createElement("h2", {}, [
		createElement("button", { type: "button", class: "collapse-toggle", "aria-expanded": "false", title: "Show details", text: entry.name }),
		...entry.symbols.map(createSymbol),
	]);

	const statusGroup = createElement("fieldset", { class: "status-group" }, [
		createElement("legend", { class: "visually-hidden", text: `Status for ${entry.name}` }),
		...STATUSES.map((statusOption) => {
			const radio = createElement("input", { type: "radio", name: `status-${entry.id}`, value: statusOption });
			radio.checked = statusOption === status;
			return createElement("label", { class: `status-${statusOption}` }, [radio, ` ${STATUS_LABELS[statusOption]}`]);
		}),
	]);

	const updatedAt = progress[entry.id]?.updatedAt;
	const statusNote = createElement("span", { class: "status-note", text: updatedAt && status !== "open" ? `${STATUS_LABELS[status]} ${formatDate(updatedAt)}` : "" });

	const links = createElement("p", { class: "links" });
	if (entry.searchUrl) links.append(createExternalLink(entry.searchUrl, "Search page"));
	if (entry.searchUrl && entry.optOutUrl && entry.searchUrl !== entry.optOutUrl) links.append(" · ");
	if (entry.optOutUrl && entry.optOutUrl !== entry.searchUrl) links.append(createExternalLink(entry.optOutUrl, "Opt-out page"));
	if (entry.searchUrl && entry.searchUrl === entry.optOutUrl) links.firstChild.textContent = "Search & opt-out page";

	const instructions = createElement("details", { class: "instructions" }, [createElement("summary", { text: "Instructions" })]);
	const instructionsBody = createElement("div");
	// Generated by scripts/extract.py: text is escaped, only <p> and <a> are emitted
	instructionsBody.innerHTML = entry.instructionsHtml;
	instructions.append(instructionsBody);

	const body = createElement("div", { class: "entry-body" }, [links, instructions]);
	article.append(createElement("div", { class: "entry-header" }, [heading, statusGroup, statusNote]), body);
	return article;
}

function renderSummary() {
	const counts = Object.fromEntries(STATUSES.map((statusOption) => [statusOption, 0]));
	for (const entry of listData.entries) counts[statusOf(entry.id)]++;
	const doneCount = counts.removed + counts["not-present"];
	summaryElement.textContent = `${doneCount} of ${listData.entries.length} done (${counts.removed} removed · ${counts["not-present"]} not present) · ${counts.requested} requested · ${counts.open} open`;
	progressBarElement.max = listData.entries.length;
	progressBarElement.value = doneCount;
}

function applyFilters() {
	const visibleStatuses = new Set([...filtersElement.querySelectorAll("input:checked")].map((checkbox) => checkbox.value));
	for (const article of entryListElement.children) {
		article.hidden = !visibleStatuses.has(article.dataset.status);
	}
}

function render() {
	entryListElement.replaceChildren(...listData.entries.map(renderEntry));
	renderSummary();
	applyFilters();
}

async function saveProgress() {
	saveStatusElement.textContent = "Saving…";
	try {
		const response = await fetch("/api/progress", {
			method: "PUT",
			headers: { "Content-Type": "application/json" },
			body: JSON.stringify(progress),
		});
		if (!response.ok) throw new Error(`${response.status} ${await response.text()}`);
		saveStatusElement.textContent = "Saved.";
	} catch (error) {
		saveStatusElement.textContent = `Save failed: ${error.message}`;
	}
}

entryListElement.addEventListener("change", (event) => {
	if (event.target.type !== "radio") return;
	const article = event.target.closest(".entry");
	const newStatus = event.target.value;
	if (newStatus === "open") delete progress[article.id];
	else progress[article.id] = { status: newStatus, updatedAt: new Date().toISOString() };

	const wasExpanded = article.classList.contains("expanded");
	const replacement = renderEntry(listData.entries.find((entry) => entry.id === article.id));
	if (wasExpanded) {
		replacement.classList.add("expanded");
		replacement.querySelector(".collapse-toggle").setAttribute("aria-expanded", "true");
	}
	article.replaceWith(replacement);
	replacement.querySelector(`input[value="${newStatus}"]`).focus();

	renderSummary();
	applyFilters();
	saveProgress();
});

// Done entries collapse to their header; the name button expands them
entryListElement.addEventListener("click", (event) => {
	const toggle = event.target.closest(".collapse-toggle");
	if (!toggle) return;
	const article = toggle.closest(".entry");
	if (!article.classList.contains("done")) return;
	const isExpanded = article.classList.toggle("expanded");
	toggle.setAttribute("aria-expanded", String(isExpanded));
});

filtersElement.addEventListener("change", applyFilters);

async function initialize() {
	renderLegend();
	try {
		const response = await fetch("/api/progress");
		if (!response.ok) throw new Error(`${response.status}`);
		progress = await response.json();
	} catch (error) {
		saveStatusElement.textContent = `Could not load saved progress (${error.message}). Changes will not be saved.`;
	}
	render();
}

initialize();
