import listData from "./entries.json";
import { STATUSES, createEmptyDocument, normalizeDocument } from "./storage/schema.js";
import { loadLocalProgress, saveLocalProgress } from "./storage/local.js";
import { markDirty, initCloudSync, pullAndMerge, pushIfDirty, startAutoSync } from "./storage/cloud.js";
import { exportDocument, readImportFile, applyImport } from "./importExport.js";
import { loadAuthState, signInUrl, signOutUrl } from "./auth.js";

const STATUS_LABELS = { open: "Open", requested: "Requested", removed: "Removed", "not-present": "Not Present" };
// Finished entries collapse to their header and count toward progress
const DONE_STATUSES = new Set(["removed", "not-present"]);

const entryListElement = document.getElementById("entry-list");
const summaryElement = document.getElementById("summary");
const progressBarElement = document.getElementById("progress-bar");
const legendElement = document.getElementById("legend");
const filtersElement = document.getElementById("filters");
const saveStatusElement = document.getElementById("save-status");
const syncStatusElement = document.getElementById("sync-status");
const authControlsElement = document.getElementById("auth-controls");
const exportButton = document.getElementById("export-json");
const importInput = document.getElementById("import-json");
const clearButton = document.getElementById("clear-progress");

let progressDoc = createEmptyDocument();

function statusOf(entryId) {
	return progressDoc.entries[entryId]?.status ?? "open";
}

function createElement(tagName, attributes = {}, children = []) {
	const element = document.createElement(tagName);
	for (const [attributeName, attributeValue] of Object.entries(attributes)) {
		if (attributeName === "text") element.textContent = attributeValue;
		else element.setAttribute(attributeName, attributeValue);
	}
	element.append(...children);
	return element;
}

function createSymbol(symbol) {
	const meaning = listData.symbolMeanings[symbol];
	return createElement("span", { class: "symbol", title: meaning, "aria-label": meaning, role: "img", text: symbol });
}

function createExternalLink(url, label) {
	return createElement("a", { href: url, target: "_blank", rel: "noopener noreferrer", text: label });
}

function formatDate(isoTimestamp) {
	return new Date(isoTimestamp).toLocaleDateString(undefined, { year: "numeric", month: "short", day: "numeric" });
}

function renderLegend() {
	legendElement.replaceChildren("Key: ");
	for (const [symbol, meaning] of Object.entries(listData.symbolMeanings)) {
		legendElement.append(createSymbol(symbol), ` ${meaning}. `);
	}
}

function renderEntry(entry) {
	const status = statusOf(entry.id);
	const article = createElement("article", { class: DONE_STATUSES.has(status) ? "entry done" : "entry", id: entry.id, "data-status": status });

	const heading = createElement("h2", {}, [
		createElement("button", { type: "button", class: "collapse-toggle", "aria-expanded": "false", title: "Show details", text: entry.name }),
		...entry.symbols.map(createSymbol),
	]);

	const statusGroup = createElement("fieldset", { class: "status-group" }, [
		createElement("legend", { class: "visually-hidden", text: `Status for ${entry.name}` }),
		...STATUSES.map((statusOption) => {
			const radio = createElement("input", { type: "radio", name: `status-${entry.id}`, value: statusOption });
			radio.checked = statusOption === status;
			return createElement("label", { class: `status-${statusOption}` }, [radio, ` ${STATUS_LABELS[statusOption]}`]);
		}),
	]);

	const statusChangedAt = progressDoc.entries[entry.id]?.statusChangedAt;
	const statusNote = createElement("span", { class: "status-note", text: statusChangedAt && status !== "open" ? `${STATUS_LABELS[status]} ${formatDate(statusChangedAt)}` : "" });

	const links = createElement("p", { class: "links" });
	if (entry.searchUrl) links.append(createExternalLink(entry.searchUrl, "Search page"));
	if (entry.searchUrl && entry.optOutUrl && entry.searchUrl !== entry.optOutUrl) links.append(" · ");
	if (entry.optOutUrl && entry.optOutUrl !== entry.searchUrl) links.append(createExternalLink(entry.optOutUrl, "Opt-out page"));
	if (entry.searchUrl && entry.searchUrl === entry.optOutUrl) links.firstChild.textContent = "Search & opt-out page";

	const instructions = createElement("details", { class: "instructions" }, [createElement("summary", { text: "Instructions" })]);
	const instructionsBody = createElement("div");
	// Generated by scripts/extract.py: text is escaped, only <p> and <a> are emitted
	instructionsBody.innerHTML = entry.instructionsHtml;
	instructions.append(instructionsBody);

	const notesId = `notes-${entry.id}`;
	const notesField = createElement("textarea", { id: notesId, class: "notes", rows: "2" });
	notesField.value = progressDoc.entries[entry.id]?.notes ?? "";
	const notes = createElement("p", { class: "notes-wrapper" }, [createElement("label", { for: notesId, text: "Notes" }), notesField]);

	const body = createElement("div", { class: "entry-body" }, [links, instructions, notes]);
	article.append(createElement("div", { class: "entry-header" }, [heading, statusGroup, statusNote]), body);
	return article;
}

function renderSummary() {
	const counts = Object.fromEntries(STATUSES.map((statusOption) => [statusOption, 0]));
	for (const entry of listData.entries) counts[statusOf(entry.id)]++;
	const doneCount = counts.removed + counts["not-present"];
	summaryElement.textContent = `${doneCount} of ${listData.entries.length} done (${counts.removed} removed · ${counts["not-present"]} not present) · ${counts.requested} requested · ${counts.open} open`;
	progressBarElement.max = listData.entries.length;
	progressBarElement.value = doneCount;
}

function applyFilters() {
	const visibleStatuses = new Set([...filtersElement.querySelectorAll("input:checked")].map((checkbox) => checkbox.value));
	for (const article of entryListElement.children) {
		article.hidden = !visibleStatuses.has(article.dataset.status);
	}
}

function render() {
	entryListElement.replaceChildren(...listData.entries.map(renderEntry));
	renderSummary();
	applyFilters();
}

// Single write path: stamps modifiedAt (and statusChangedAt on status change),
// saves locally, and marks the document dirty for the next cloud sync.
function updateEntry(slug, changes) {
	const existing = progressDoc.entries[slug] ?? {};
	const now = new Date().toISOString();
	const next = { ...existing, modifiedAt: now };

	if ("status" in changes) {
		if (changes.status && changes.status !== "open") {
			next.status = changes.status;
			next.statusChangedAt = now;
		} else {
			delete next.status;
			delete next.statusChangedAt;
		}
	}
	if ("notes" in changes) {
		if (changes.notes) next.notes = changes.notes;
		else delete next.notes;
	}

	if (!next.status && !next.notes) delete progressDoc.entries[slug];
	else progressDoc.entries[slug] = next;

	persist();
}

function persist() {
	const saved = saveLocalProgress(progressDoc);
	saveStatusElement.textContent = saved ? "Saved in this browser." : "Progress can't be saved in this browser — export a backup so you don't lose it.";
	markDirty();
}

entryListElement.addEventListener("change", (event) => {
	if (event.target.type !== "radio") return;
	const article = event.target.closest(".entry");
	const newStatus = event.target.value;
	updateEntry(article.id, { status: newStatus });

	const wasExpanded = article.classList.contains("expanded");
	const replacement = renderEntry(listData.entries.find((entry) => entry.id === article.id));
	if (wasExpanded) {
		replacement.classList.add("expanded");
		replacement.querySelector(".collapse-toggle").setAttribute("aria-expanded", "true");
	}
	article.replaceWith(replacement);
	replacement.querySelector(`input[value="${newStatus}"]`).focus();

	renderSummary();
	applyFilters();
});

// Done entries collapse to their header; the name button expands them
entryListElement.addEventListener("click", (event) => {
	const toggle = event.target.closest(".collapse-toggle");
	if (!toggle) return;
	const article = toggle.closest(".entry");
	if (!article.classList.contains("done")) return;
	const isExpanded = article.classList.toggle("expanded");
	toggle.setAttribute("aria-expanded", String(isExpanded));
});

// Notes don't trigger a re-render (would drop focus mid-typing); localStorage
// writes are cheap enough to do on every keystroke.
entryListElement.addEventListener("input", (event) => {
	if (!event.target.classList.contains("notes")) return;
	const entryId = event.target.closest(".entry").id;
	updateEntry(entryId, { notes: event.target.value });
});

filtersElement.addEventListener("change", applyFilters);

exportButton.addEventListener("click", () => exportDocument(progressDoc));

importInput.addEventListener("change", async () => {
	const file = importInput.files[0];
	importInput.value = "";
	if (!file) return;
	try {
		const { normalized, importedCount, skippedCount } = await readImportFile(file);
		const mergeChosen = confirm(
			`Import ${importedCount} site(s)${skippedCount ? `, skip ${skippedCount} invalid` : ""}.\n\n` +
				"OK = Merge with existing progress (newest change per site wins)\nCancel = Replace existing progress entirely",
		);
		progressDoc = applyImport(progressDoc, normalized, mergeChosen ? "merge" : "replace");
		saveLocalProgress(progressDoc);
		markDirty();
		render();
		saveStatusElement.textContent = `Imported ${importedCount} site(s)${skippedCount ? `, skipped ${skippedCount} invalid` : ""}.`;
	} catch (error) {
		saveStatusElement.textContent = `Import failed: ${error.message}`;
	}
});

clearButton.addEventListener("click", () => {
	if (!confirm("Clear all progress? This can't be undone unless you exported a backup.")) return;
	progressDoc = createEmptyDocument();
	saveLocalProgress(progressDoc);
	markDirty();
	render();
});

function renderAuthControls(user) {
	authControlsElement.replaceChildren();
	if (user) {
		authControlsElement.append(
			`Syncing as ${user.username} · `,
			createElement("button", { type: "button", id: "sync-now", text: "Sync now" }),
			" · ",
			createExternalLinkless(signOutUrl(), "Sign out"),
			" · ",
			createExternalLinkless("/privacy.html", "Delete my cloud data"),
		);
	} else {
		authControlsElement.append(createExternalLinkless(signInUrl(), "Sign in with GitHub to sync across devices"));
	}
}

// Same-origin auth/nav links: no target="_blank", unlike createExternalLink
function createExternalLinkless(url, label) {
	return createElement("a", { href: url, text: label });
}

authControlsElement.addEventListener("click", (event) => {
	if (event.target.id === "sync-now") pushIfDirty();
});

async function initialize() {
	renderLegend();
	progressDoc = normalizeDocument(loadLocalProgress() ?? createEmptyDocument());
	render();

	const user = await loadAuthState();
	renderAuthControls(user);
	initCloudSync({
		onStatus: (text) => {
			syncStatusElement.textContent = text;
		},
		getLocalDocument: () => progressDoc,
		applyDocument: (merged) => {
			progressDoc = merged;
			render();
		},
	});

	if (user) {
		syncStatusElement.hidden = false;
		await pullAndMerge();
		startAutoSync();
	} else {
		syncStatusElement.hidden = true;
	}
}

initialize();
